---
title: "HADACA3 Framework - Generate data for data challenge hadaca"
subtitle: "Meta analysis"
author: ""
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    self_contained: false
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
---

# Aggregated and atomic scores per method

```{r, echo=FALSE, eval=TRUE}
knitr::opts_chunk$set(collapse=TRUE, comment = "#>", fig.width=12, fig.height=12, eval=TRUE, echo=TRUE, results="verbatim", dpi=75)
```

```{r loading_pckgs, echo=FALSE, message=FALSE}
library(yaml)
library(DT)
library(stringr)
library(dplyr)
library(ggplot2)
theme_set(theme_light())
library(plotly)
library(fs)

library(furrr)
# library(utils)


# okabe <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")


source(utils_script)
# source("utils/data_processing.R")


mamximum_dataset_name = 6
```


# read 
```{r Late_integration_pipeline improved,eval=TRUE}




list_wd <- strsplit(getwd(), '/')[[1]]
if (list_wd[length(list_wd)] == 'hadaca3_framework') {
  score_files <- list.files(path = "./output/scores/", full.names = TRUE)
} else {
  # score_files <- list.files(pattern = 'score-li*', full.names = TRUE)
  # score_files <- system("find . -maxdepth 1 -type f -name 'score-li*'", intern = TRUE)
  score_files <- dir_ls(".", regexp = "score-li.*")
}

plan(multisession,workers=4) # workers=25
# plan(sequential)


process_file <- function(score_file) {
  base_name <- basename(score_file)
  components <- str_match(base_name, 
    "score-li-(.+)_(.+)_mixRNA_(.+)_(.+)_RNA_(.+)_(.+)_scRNA_(.+)_(.+)_(.+)_mixMET_(.+)_(.+)_MET_(.+)_(.+)_(.+)_(.+).h5")[2:16]

  # If file name doesn't match expected pattern, skip
  if (any(is.na(components))) return(NULL)

  scores <- tryCatch({
    s <- read_hdf5(score_file)
    gc()
    s
  }, error = function(e) {
    message("Error reading file: ", score_file)
    message(e)
    NULL
  })

  # scores <- tryCatch({
  #   read_hdf5(score_file)
  # }, error = function(e) return(NULL))

  if (is.null(scores)) return(NULL)

  cbind(
    data.frame(
      dataset = components[1],
      ref = components[2],
      preprocessing_mixRNA = components[3],
      feature_selection_mixRNA = components[4],
      preprocessing_RNA = components[5],
      feature_selection_RNA = components[6],
      preprocessing_scRNA = components[7],
      feature_selection_scRNA = components[8],
      deconvolution_rna = components[9],
      preprocessing_mixMET = components[10],
      feature_selection_mixMET = components[11],
      preprocessing_MET = components[12],
      feature_selection_MET = components[13],
      deconvolution_met = components[14],
      late_integration = components[15],
      stringsAsFactors = FALSE
    ),
    scores
  )
}

# Process files in parallel
# results_list <- lapply(score_files, process_file)

results_list <- future_map(score_files, function(f) {
  tryCatch(process_file(f), error = function(e) NULL)
})


all_functions_li <- c(
  'preprocessing_mixRNA', 'feature_selection_mixRNA',
  'preprocessing_RNA', 'feature_selection_RNA',
  'preprocessing_scRNA', 'feature_selection_scRNA', 'deconvolution_rna',
  'preprocessing_mixMET', 'feature_selection_mixMET',
  'preprocessing_MET', 'feature_selection_MET', 'deconvolution_met',
  'late_integration'
)

if(length(results_list) != 0)  {
  results_li <- do.call(rbind, results_list)

  results_li %>%
    # filter(dc==2) %>%
    group_by(late_integration) %>%
    summarise(GlobalScore = median(score_aggreg)) %>%
    arrange(desc(GlobalScore))

  results_li_arrange = results_li %>%
    group_by(preprocessing_mixRNA, feature_selection_mixRNA, 
            preprocessing_RNA, feature_selection_RNA, 
            preprocessing_scRNA, feature_selection_scRNA, deconvolution_rna, 
            preprocessing_mixMET,feature_selection_mixMET, 
            preprocessing_MET, feature_selection_MET, deconvolution_met, 
            late_integration, .groups = "keep") %>% 
    summarise(GlobalScore = median(score_aggreg)) %>%
    arrange(desc(GlobalScore)) 



  # Optional: reorder factors
  all_data_used <- c('dataset', 'ref')
  for (data_used in all_data_used) {
    results_li[[data_used]] <- factor(results_li[[data_used]], levels = unique(results_li[[data_used]]))
  }


  # Optional: order other factors based on performance on 'invitro1'
  if ("invitro1" %in% results_li$dataset) {
    for (fun in all_functions_li) {
      results_li[[fun]] <- factor(results_li[[fun]],
        levels = unique(results_li[[fun]][order(results_li$score_aggreg[results_li$dataset == 'invitro1'], decreasing = TRUE)]))
    }
  }
}else{
results_li = all_functions_li
}

# dataset_names <- unique(results_li$dataset)
if (is.data.frame(results_li)) {
  dynamic_name_li <- paste0("results_li_",paste(unique(results_li$dataset), collapse = "_") )
  nb_datasets = length(unique(results_li$dataset))
  if( nb_datasets > mamximum_dataset_name ){
    dynamic_name_li = paste0("results_li_",paste0(nb_datasets,"-datasets"))
  }
    
  
}else{
  dynamic_name_li <- paste0("results_li_empty")
} 

  # Assign dynamically to global environment
# assign("results_li",dynamic_name_li, envir = .GlobalEnv)

# Write compressed output
write.csv(results_li, file = gzfile(paste0(dynamic_name_li, ".csv.gz")), row.names = FALSE)
# results_li = read.csv(file = gzfile("results_li.csv.gz"))



```



```{r display LI table,echo=FALSE,eval=TRUE }
index_aggreg <- which(names(results_li) == "score_aggreg")
index_dataset <- which(names(results_li) == "dataset")

max_rows = 4000

if(is.data.frame(results_li) 
# & (nrow(results_li) < max_rows)
) {

datatable(
  results_li[, c(index_dataset,1:length(all_functions_li)+2, index_aggreg)],
  extensions = 'Buttons',
  rownames = FALSE, 
  options = list(
    pageLength = 15,
    dom = 'Bfrtip',  # This includes the Buttons extension in the layout
    buttons = list(
      list(
        extend = 'colvis',
        text = 'Show/Hide Columns',
        columns = ':not(:first-child)'  # This allows all columns except the first to be toggled
      )
    )
  )
)
}
```



# Early integration_table 
```{r Early_integration pipeline,echo=FALSE,eval=TRUE}


list_wd <- strsplit(getwd(), '/')[[1]]
if (list_wd[length(list_wd)] == 'hadaca3_framework') {
  score_files_ei <- list.files(path = "./output/scores/", full.names = TRUE)
} else {
  # score_files_ei <- list.files(pattern = 'score-ei*', full.names = TRUE)
  score_files_ei <- dir_ls(".", regexp = "score-ei*")

  # score_files_ei <- system("find . -maxdepth 1 -type f -name 'score-ei*'", intern = TRUE)

}


# plan(multisession)


process_file_ei <- function(score_file) {
  base_name <- basename(score_file)

  # Extract metadata from file name
  components <- str_match(base_name, 
    "score-ei-(.+)_(.+)_mixRNA_(.+)_(.+)_RNA_(.+)_(.+)_scRNA_(.+)_(.+)_mixMET_(.+)_(.+)_MET_(.+)_(.+)_(.+)_(.+).h5")[2:15]

  # Skip file if regex fails
  if (any(is.na(components))) return(NULL)

  # Read HDF5 file safely
  scores <- tryCatch({
    read_hdf5(score_file)
  }, error = function(e) return(NULL))

  if (is.null(scores)) return(NULL)

  # Combine metadata and scores
  cbind(
    data.frame(
      dataset = components[1],
      ref = components[2],
      preprocessing_mixRNA = components[3],
      feature_selection_mixRNA = components[4],
      preprocessing_RNA = components[5],
      feature_selection_RNA = components[6],
      preprocessing_scRNA = components[7],
      feature_selection_scRNA = components[8],
      preprocessing_mixMET = components[9],
      feature_selection_mixMET = components[10],
      preprocessing_MET = components[11],
      feature_selection_MET = components[12],
      early_integration = components[13],
      deconvolution = components[14],
      stringsAsFactors = FALSE
    ),
    scores
  )
}

results_list_ei <- future_map(score_files_ei, function(f) {
  tryCatch(process_file_ei(f), error = function(e) NULL)
})

all_functions_ei <- c(
    'preprocessing_mixRNA', 'feature_selection_mixRNA',
    'preprocessing_RNA', 'feature_selection_RNA',
    'preprocessing_scRNA', 'feature_selection_scRNA',
    'preprocessing_mixMET', 'feature_selection_mixMET',
    'preprocessing_MET', 'feature_selection_MET',
    'early_integration', 'deconvolution'
  )

  

if(length(results_list_ei) != 0  ){
  results_ei <- do.call(rbind, Filter(Negate(is.null), results_list_ei))

  if ("invitro1" %in% results_ei$dataset) {
    # all_functions_ei <- c(
    #   'preprocessing_mixRNA', 'feature_selection_mixRNA',
    #   'preprocessing_RNA', 'feature_selection_RNA',
    #   'preprocessing_scRNA', 'feature_selection_scRNA',
    #   'preprocessing_mixMET', 'feature_selection_mixMET',
    #   'preprocessing_MET', 'feature_selection_MET',
    #   'early_integration', 'deconvolution'
    # )

    for (fun in all_functions_ei) {
      results_ei[[fun]] <- factor(results_ei[[fun]],
        levels = unique(results_ei[[fun]][order(results_ei$score_aggreg[results_ei$dataset == 'invitro1'], decreasing = TRUE)]))
    }
  }

}else{
  results_ei = all_functions_ei
}

if (is.data.frame(results_ei)) {
  dynamic_name_ei <- paste0("results_ei_",paste(unique(results_ei$dataset), collapse = "_") )
  nb_datasets_ei = length(unique(results_ei$dataset))

    if( nb_datasets_ei > mamximum_dataset_name  ){
    dynamic_name_ei = paste0("results_ei_",paste0(nb_datasets_ei,"-datasets"))
  }
}else{
  dynamic_name_ei <- paste0("results_ei_empty")
} 

  # Assign dynamically to global environment
# assign("results_ei",dynamic_name_ei, envir = .GlobalEnv)



write.csv(results_ei, file = gzfile(paste0(dynamic_name_ei, ".csv.gz")), row.names = FALSE)




```

```{r display EI table,echo=FALSE,eval=TRUE }
index_aggreg_ei <- which(names(results_ei) == "score_aggreg")
index_dataset_ei <- which(names(results_ei) == "dataset")

max_rows = 4000

if(is.data.frame(results_ei) 
# & (nrow(results_ei) < max_rows)
) {

  datatable(
    # results_ei[, c(1:length(all_functions_ei)+2, index_aggreg_ei)],
    results_ei[, c(index_dataset_ei,1:length(all_functions_ei)+2, index_aggreg_ei)],
    rownames = FALSE, 
    extensions = 'Buttons',
    options = list(
      pageLength = 10,
      dom = 'Bfrtip',  # This includes the Buttons extension in the layout
      buttons = list(
        list(
          extend = 'colvis',
          text = 'Show/Hide Columns',
          columns = ':not(:first-child)'  # This allows all columns except the first to be toggled
        )
      )
    )
  )
}

```



# Execute 08_meta : 

```{r 08_meta,eval=TRUE }
rmarkdown::render(input ='08_metaanalysis.Rmd',envir = parent.frame());
```

# Visualisations of the top methods

## top 5 best methods

```{r table_top5best_by_dataset, echo=FALSE, eval=TRUE}
#if more than 5 ex aequo combination, then taking them all
if (length(which(results_li_arrange$GlobalScore == max(results_li_arrange$GlobalScore))) > 5) {
  results_li_top5best = results_li_arrange[which(results_li_arrange$GlobalScore == max(results_li_arrange$GlobalScore)), ]
} else {
  results_li_top5best = results_li_arrange[1:5,]
}

results_li_top5best <- results_li_top5best[complete.cases(results_li_top5best[, 1:13]), ]


datatable(
  results_li_top5best[,-14],
  extensions = 'Buttons',
  options = list(
    pageLength = 10,
    dom = 'Bfrtip',  # This includes the Buttons extension in the layout
    buttons = list(
      list(
        extend = 'colvis',
        text = 'Show/Hide Columns',
        columns = ':not(:first-child)'  # This allows all columns except the first to be toggled
      )
    )
  )
)
```


```{r scatter_plot_top5best_by_dataset,eval=TRUE, warning=FALSE, echo=FALSE, message=TRUE}

test_dataset = 'invitro1'
number_part = str_sub(test_dataset,-1)
name_part = str_sub(test_dataset,end=str_length(test_dataset)-1)


ground_truth_name_file = paste0("groundtruth",number_part,'_',name_part,"_pdac.h5")
ground_truth_invitro1 = read_hdf5(paste0(ground_truth_name_file))$groundtruth



prediction_file = sapply(1:nrow(results_li_top5best), function(i){
  paste0("pred-li-",paste(c("invitro1", "ref", as.character(unlist(results_li_top5best[i, 1:13]))),collapse = "_") ,".h5")
})
pred = lapply(prediction_file, \(path){read_hdf5(path)}) 


df_scatter = do.call(
  what = rbind,
  args = lapply(levels(results_li$dataset), function(data) { # we remove in vivo
    


    print(data)



    #parse the dataset name to get the groundtruth file name. invitro1 is split to invitro and 1
    number_part = str_sub(data,-1)
    name_part = str_sub(data,end=str_length(data)-1)
    ground_truth_name_file = paste0("groundtruth",number_part,'_',name_part,"_pdac.h5")
    A_real = read_hdf5(paste0(ground_truth_name_file))$groundtruth

    ground_truth_data = t(A_real)
    ground_truth_data = tidyr::pivot_longer(
      as.data.frame(ground_truth_data),
      cols = colnames(ground_truth_data),
      names_to = "cell_type",
      values_to = "true_prop"
    )
    

    
    prediction_file = sapply(1:nrow(results_li_top5best), function(i){
      paste0("pred-li-",paste(c(data, "ref", as.character(unlist(results_li_top5best[i, 1:13]))),collapse = "_") ,".h5")
    })
    # pred = lapply(prediction_file, \(path){read_hdf5(path)$pred})

    pred = lapply(prediction_file, function(path){
      A_pred = read_hdf5(path)$pred
      if (nrow(A_pred)==(nrow(A_real)+1)) {
        A_pred = A_pred[rownames(A_pred) %in% rownames(A_real),]
      }
      if(nrow(A_pred)+1==(nrow(A_real))){
        extra_type = matrix(0,ncol=ncol(A_real),nrow=1)
        rownames(extra_type) = rownames(A_real)[!(rownames(A_real) %in%rownames(A_pred))]
        A_pred = rbind(A_pred,extra_type)
      }
      return(A_pred)
    })

    method_i = 1
    prediction_data = t(pred[[method_i]])
    prediction_data = tidyr::pivot_longer(
      as.data.frame(prediction_data),
      cols = everything(),
      names_to = "cell_type",
      values_to = "pred_prop"
    )
    prediction_data[,"method"] = paste0("method top", method_i)
    # print(prediction_data)
    
    for (method_i in 2:nrow(results_li_top5best)) {
      prediction_data_tmp = t(pred[[method_i]])
      prediction_data_tmp = tidyr::pivot_longer(
        as.data.frame(prediction_data_tmp),
        cols = everything(),
        names_to = "cell_type",
        values_to = "pred_prop"
      )
      prediction_data_tmp[,"method"] = paste0("method top", method_i)
      prediction_data = rbind(prediction_data, prediction_data_tmp)
    }


    ground_truth_data = rbind(ground_truth_data, ground_truth_data,
                              ground_truth_data, ground_truth_data, ground_truth_data)
  
    
    if (data == "invivo1" || data == "invivo2") {
      prediction_data = prediction_data[prediction_data$cell_type == "classic" | prediction_data$cell_type == "basal", ]
    }
    # print(prediction_data)
    # print(ground_truth_data)
    prop_data = cbind(prediction_data, ground_truth_data[,"true_prop"], Dataset = data)

  })
)
df_scatter$Dataset = factor(df_scatter$Dataset, levels = unique(results_li$dataset))
df_scatter$cell_type = factor(df_scatter$cell_type, levels = rownames(ground_truth_invitro1))


df_scatter$method = factor(df_scatter$method)

# print(df_scatter)

scatter_prop = ggplot(df_scatter) +
  facet_wrap( ~ Dataset) +
  geom_abline(intercept = 0, slope = 1, linetype = 3, linewidth = 0.25) +
  geom_point(aes(x = true_prop, y = pred_prop, col = method, shape = cell_type)) +
  coord_cartesian(
    xlim = c(0,1),
    ylim = c(0,1)
  ) +
  labs(
    x = "Ground truth proportion",
    y = "Prediction",
    title = paste("Proportions predicted by top 5 best method vs true ones for all datasets")
  ) +
  scale_x_continuous(
    labels = scales::percent
  ) +
  scale_y_continuous(
    labels = scales::percent
  ) +
  scale_color_discrete(
    name = "Cell type"
  ) +
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5))

pp = plotly::ggplotly(scatter_prop, width = 900, height = 1000)
# pp
pp = plotly::layout(pp, legend = list(orientation = 'h'))
pp
# invisible(
  # lapply(seq_along(pp$x$layout$shapes), \(i){ # ça ne regle pas entierement le pb, ils sont toujours sur les plots du dessus
# 
#   # if a strip shape (using the strip color), reduce the height of the strip box
#   if(isTRUE(pp$x$layout$shapes[[i]]$fillcolor == "rgba(179,179,179,1)")) {
#    pp$x$layout$shapes[[i]]$y1 <<- 18    # base at 23.379
#   }
#   # there are less annotations than shapes
#   if(i <= length(pp$x$layout$annotations)) {
#     # reduce the font size of the strip text
#     if(any(pp$x$layout$annotations[[i]]$text %in% unique(df_metric$metric_name))) {
#       pp$x$layout$annotations[[i]]$font$size <<- 11   # base at 11.6895
#     }
#   }
# })
# )
# pp
```


## top 5 worst methods

```{r table_top5worst_by_dataset, echo=FALSE,eval=TRUE}
#if more than 5 ex aequo combination, then taking them all
if (length(which(results_li_arrange$GlobalScore == min(results_li_arrange$GlobalScore))) > 5) {
  results_li_top5worst = results_li_arrange[which(results_li_arrange$GlobalScore == min(results_li_arrange$GlobalScore)), ]
} else {
  results_li_top5worst = results_li_arrange[(nrow(results_li_arrange)-4):nrow(results_li_arrange),]
}

datatable(
  results_li_top5worst[,-14],
  extensions = 'Buttons',
  options = list(
    pageLength = 10,
    dom = 'Bfrtip',  # This includes the Buttons extension in the layout
    buttons = list(
      list(
        extend = 'colvis',
        text = 'Show/Hide Columns',
        columns = ':not(:first-child)'  # This allows all columns except the first to be toggled
      )
    )
  )
)
```


```{r scatter_plot_top5worst_by_dataset, warning=FALSE, echo=FALSE, message=TRUE,eval=FALSE}

test_dataset = 'invitro1'
# name_part <- gsub("[0-9]+$", "", test_dataset)
# number_part <- gsub("[^0-9]", "", test_dataset)
number_part = str_sub(test_dataset,-1)
name_part = str_sub(test_dataset,end=str_length(test_dataset)-1)

ground_truth_name_file = paste0("groundtruth",number_part,'_',name_part,"_pdac.h5")
ground_truth_invitro1 = read_hdf5(paste0(ground_truth_name_file))$groundtruth



prediction_file = sapply(1:nrow(results_li_top5worst), function(i){
  paste0("pred-li-",paste(c("invitro1", "ref", as.character(unlist(results_li_top5worst[i, 1:13]))),collapse = "_") ,".h5")
})                                                   
pred = lapply(prediction_file, \(path){read_hdf5(path)})  

df_scatter = do.call(
  what = rbind,
  args = lapply(levels(results_li$dataset), function(data) { # we remove in vivo
    
    

    # name_part <- gsub("[0-9]+$", "", data)
    # number_part <- gsub("[^0-9]", "", data)
    number_part = str_sub(data,-1)
    name_part = str_sub(data,end=str_length(data)-1)
    ground_truth_name_file = paste0("groundtruth",number_part,'_',name_part,"_pdac.h5")
    A_real = read_hdf5(paste0(ground_truth_name_file))$groundtruth

    ground_truth_data = t(A_real)
    ground_truth_data = tidyr::pivot_longer(
      as.data.frame(ground_truth_data),
      cols = colnames(ground_truth_data),
      names_to = "cell_type",
      values_to = "true_prop"
    )

    prediction_file = sapply(1:nrow(results_li_top5worst), function(i){
      paste0("pred-li-",paste(c(data, "ref", as.character(unlist(results_li_top5worst[i, 1:13]))),collapse = "_") ,".h5")
    })
    # pred = lapply(prediction_file, \(path){read_hdf5(path)$pred})
      pred = lapply(prediction_file, function(path){
      A_pred = read_hdf5(path)$pred
      if (nrow(A_pred)==(nrow(A_real)+1)) {
        A_pred = A_pred[rownames(A_pred) %in% rownames(A_real),]
      }
      if(nrow(A_pred)+1==(nrow(A_real))){
        extra_type = matrix(0,ncol=ncol(A_real),nrow=1)
        rownames(extra_type) = rownames(A_real)[!(rownames(A_real) %in%rownames(A_pred))]
        A_pred = rbind(A_pred,extra_type)
      }
      return(A_pred)
    })
    
    method_i = 1
    prediction_data = t(pred[[method_i]])
    prediction_data = tidyr::pivot_longer(
      as.data.frame(prediction_data),
      cols = everything(),
      names_to = "cell_type",
      values_to = "pred_prop"
    )
    prediction_data[,"method"] = paste0("method top", method_i)
    # print(prediction_data)
    
    for (method_i in 2:nrow(results_li_top5worst)) {
      prediction_data_tmp = t(pred[[method_i]])
      prediction_data_tmp = tidyr::pivot_longer(
        as.data.frame(prediction_data_tmp),
        cols = everything(),
        names_to = "cell_type",
        values_to = "pred_prop"
      )
      prediction_data_tmp[,"method"] = paste0("method top", method_i)
      prediction_data = rbind(prediction_data, prediction_data_tmp)
    }



    ground_truth_data = rbind(ground_truth_data, ground_truth_data,
                              ground_truth_data, ground_truth_data, ground_truth_data)

    if (data == "invivo1" || data == "invivo2") {
      prediction_data = prediction_data[prediction_data$cell_type == "classic" | prediction_data$cell_type == "basal", ]
    }

    prop_data = cbind(prediction_data, ground_truth_data[,"true_prop"], Dataset = data)
  })
)
df_scatter$Dataset = factor(df_scatter$Dataset, levels = unique(results_li$dataset))
df_scatter$cell_type = factor(df_scatter$cell_type, levels = rownames(ground_truth_invitro1))
df_scatter$method = factor(df_scatter$method)

# print(df_scatter)

scatter_prop = ggplot(df_scatter) +
  facet_wrap( ~ Dataset) +
  geom_abline(intercept = 0, slope = 1, linetype = 3, linewidth = 0.25) +
  geom_point(aes(x = true_prop, y = pred_prop, col = method, shape = cell_type)) +
  coord_cartesian(
    xlim = c(0,1),
    ylim = c(0,1)
  ) +
  labs(
    x = "Ground truth proportion",
    y = "Prediction",
    title = paste("Proportions predicted by top 5 worst method vs true ones for all datasets")
  ) +
  scale_x_continuous(
    labels = scales::percent
  ) +
  scale_y_continuous(
    labels = scales::percent
  ) +
  scale_color_discrete(
    name = "Cell type"
  ) +
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5))

pp = plotly::ggplotly(scatter_prop, width = 900, height = 1000)
# pp
pp = plotly::layout(pp, legend = list(orientation = 'h'))
pp
# invisible(
  # lapply(seq_along(pp$x$layout$shapes), \(i){ # ça ne regle pas entierement le pb, ils sont toujours sur les plots du dessus
# 
#   # if a strip shape (using the strip color), reduce the height of the strip box
#   if(isTRUE(pp$x$layout$shapes[[i]]$fillcolor == "rgba(179,179,179,1)")) {
#    pp$x$layout$shapes[[i]]$y1 <<- 18    # base at 23.379
#   }
#   # there are less annotations than shapes
#   if(i <= length(pp$x$layout$annotations)) {
#     # reduce the font size of the strip text
#     if(any(pp$x$layout$annotations[[i]]$text %in% unique(df_metric$metric_name))) {
#       pp$x$layout$annotations[[i]]$font$size <<- 11   # base at 11.6895
#     }
#   }
# })
# )
# pp
```


# Visualisations of the different metrics

```{r plot_FUN, echo=FALSE, message=TRUE,eval=FALSE}
plot_aggregated_score <- function(data, x_var, y_var, title, facet_var = NULL, add_tooltip_text = FALSE) {
  
  # noBLOCK is joint with onlyOMIC late integration
  if (x_var != "early_integration" && x_var != "late_integration") {
    data = data[data$preprocessing_mixRNA != "nopp",]
    data = data[data$feature_selection_mixRNA != "nofs",]
    data = data[data$preprocessing_RNA != "nopp",]
    data = data[data$feature_selection_RNA != "nofs",]
    data = data[data$preprocessing_scRNA != "nopp",]
    data = data[data$feature_selection_scRNA != "nofs",]
    data = data[data$deconvolution_rna != "node",]
    data = data[data$preprocessing_mixMET != "nopp",]
    data = data[data$feature_selection_mixMET != "nofs",]
    data = data[data$preprocessing_MET != "nopp",]
    data = data[data$feature_selection_MET != "nofs",]
    data = data[data$deconvolution_met != "node",]
  }

  # Dynamically build aesthetics
  aes_base <- aes_string(x = x_var, y = y_var, fill = x_var)
  # aes_fill <- if (!is.null(fill_var)) aes_string(fill = fill_var) else NULL
  
  overlayer_infos_colnames = colnames(data)[c(3:15, which(colnames(data) == y_var))]
  # overlayer_infos = c("PP_RNA_mix: ", "FS_RNA_mix: ", "PP_RNA_ref: ", "FS_RNA_ref: ",
  #                     "PP_RNA_mix: ")
  overlayer_infos_colnames = overlayer_infos_colnames[-which(overlayer_infos_colnames == x_var)]
  
  
  p <- ggplot(data) +
    # geom_boxplot(aes_base) +
    geom_violin(aes_base) +
    # geom_jitter(
    #   aes_string(
    #     x = x_var, 
    #     y = y_var, 
    #     color = "dataset", 
    #     text = NULL  # Placeholder
    #     # text = paste0( 
    #     #   data[[overlayer_infos_colnames[1]]], data[[overlayer_infos_colnames[2]]],
    #     #   data[[overlayer_infos_colnames[3]]], data[[overlayer_infos_colnames[4]]],
    #     #   data[[overlayer_infos_colnames[5]]], data[[overlayer_infos_colnames[6]]],
    #     #   data[[overlayer_infos_colnames[7]]], data[[overlayer_infos_colnames[8]]],
    #     #   data[[overlayer_infos_colnames[9]]], data[[overlayer_infos_colnames[10]]],
    #     #   data[[overlayer_infos_colnames[11]]], data[[overlayer_infos_colnames[11]]],
    #     #   data[[overlayer_infos_colnames[13]]]
    #     # )
    #   ),
    #   size = 0.4, alpha = 0.5
    # ) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
      plot.title = element_text(hjust = 0.5),
      legend.position = "bottom"
    ) +
    labs(
      title = title,
      x = "Methods",
      # y = "Aggregated score",
      fill = x_var
    ) +
    scale_color_grey(start = 0.2, end = 0.2)
  
  tooltip_cols <- c(y_var,
    "preprocessing_mixRNA", "preprocessing_RNA", "preprocessing_scRNA",
    "preprocessing_mixMET", "preprocessing_MET",
    "feature_selection_mixRNA", "feature_selection_RNA", "feature_selection_scRNA",
    "feature_selection_mixMET", "feature_selection_MET",
    "deconvolution_rna", "deconvolution_met", "late_integration"
  )
  tooltip_cols_short <- c(y_var, #racourci
    "PP_mixRNA", "PP_RNA", "PP_scRNA", "PP_mixMET", "PP_MET",
    "FS_mixRNA", "FS_RNA", "FS_scRNA", "FS_mixMET", "FS_MET",
    "DE_rna", "DE_met", "LI"
  )
  # suppr_active_col 
  # active_col = which(tooltip_cols == x_var)
  # tooltip_cols = tooltip_cols[-active_col]
  # tooltip_cols_short = tooltip_cols_short[-active_col]
  # 
  # # Générer le texte dynamiquement : "Nom_colonne: valeur"
  # tooltip_text <- do.call(paste, c(
  #   lapply(1:length(tooltip_cols), function(i, col, col_short) {
  #     paste(col_short[i], ":", data[[col[i]]])
  #   }, col = tooltip_cols, col_short = tooltip_cols_short),
  #   sep = "\n"
  # ))
  # # L’injecter dans aes()
  # p$layers[[2]]$mapping$text <- aes(text = tooltip_text)$text
  
  if (!is.null(facet_var)) {
    p <- p + facet_wrap(as.formula(paste("~", facet_var)), scales = "free_x")
  }
  
  plotly::layout(
    plotly::ggplotly(p), # , tooltip = if (add_tooltip_text) "text" else NULL), 
    legend = list(orientation = 'h')
  )
}

########### BASE
add_tooltip_text = FALSE
facet_var = "dataset"
########### Only for exploration
# add_tooltip_text = TRUE
```


## Paper figures

```{r paper_figure_FUN, echo=FALSE, message=TRUE,eval=FALSE}
paper_figure <- function(data, x_var, y_var, title) {
  
  # noBLOCK is joint with onlyOMIC late integration
  if (x_var != "early_integration" && x_var != "late_integration") {
    data = data[data$preprocessing_mixRNA != "nopp",]
    data = data[data$feature_selection_mixRNA != "nofs",]
    data = data[data$preprocessing_RNA != "nopp",]
    data = data[data$feature_selection_RNA != "nofs",]
    data = data[data$preprocessing_scRNA != "nopp",]
    data = data[data$feature_selection_scRNA != "nofs",]
    data = data[data$deconvolution_rna != "node",]
    data = data[data$preprocessing_mixMET != "nopp",]
    data = data[data$feature_selection_mixMET != "nofs",]
    data = data[data$preprocessing_MET != "nopp",]
    data = data[data$feature_selection_MET != "nofs",]
    data = data[data$deconvolution_met != "node",]
  }
  
  # Dynamically build aesthetics
  aes_base <- aes_string(x = x_var, y = y_var, fill = x_var)
  # aes_fill <- if (!is.null(fill_var)) aes_string(fill = fill_var) else NULL
  

  
  p <- ggplot(data) +
    # geom_boxplot(aes_base) +
    geom_violin(aes_base) +
    # geom_jitter(
    #   aes_string(
    #     x = x_var, 
    #     y = y_var, 
    #     color = "dataset"
    #   ),
    #   size = 0.4, alpha = 0.5
    # ) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5),
      plot.title = element_text(hjust = 0.5),
      legend.position = "bottom"
    ) +
    labs(
      title = title,
      x = "Methods",
      # y = "Aggregated score",
      fill = x_var
    ) +
    scale_color_grey(start = 0.2, end = 0.2)
  
  p
}
```

```{r paper_figure_common_var_score_aggreg, echo=FALSE,eval=FALSE}
metric = "score_aggreg"
metric_title = "Aggregated score (-> 1), per dataset"
```


### PP

```{r paper_figure_combinaisons_aggregated_scores_PP, echo=FALSE, eval=FALSE, warning = FALSE }
#### MET
paper_figure(data = results_li, x_var = "preprocessing_mixMET", y_var = metric, title = metric_title)

#### RNA
paper_figure(data = results_li, x_var = "preprocessing_mixRNA", y_var = metric, title = metric_title)
```


### FS

```{r paper_figure_combinaisons_aggregated_scores_FS, echo=FALSE, eval=FALSE}
#### MET
paper_figure(data = results_li, x_var = "feature_selection_mixMET", y_var = metric, title = metric_title)

#### RNA
paper_figure(data = results_li, x_var = "feature_selection_mixRNA", y_var = metric, title = metric_title)
```

### DE

```{r paper_figure_combinaisons_aggregated_scores_DE, echo=FALSE,eval=FALSE}
#### MET
paper_figure(data = results_li, x_var = "deconvolution_met", y_var = metric, title = metric_title)

#### RNA
paper_figure(data = results_li, x_var = "deconvolution_rna", y_var = metric, title = metric_title)
```

### LI

```{r paper_figure_combinaisons_aggregated_scores_LI, echo=FALSE,eval=FALSE}
paper_figure(data = results_li, x_var = "late_integration", y_var = metric, title = metric_title)
```


## Aggregated scores

```{r common_var_score_aggreg, echo=FALSE}
metric = "score_aggreg"
metric_title = "Aggregated score (-> 1), per dataset"
```


### PP

```{r combinaisons_aggregated_scores_PP, echo=FALSE,eval=FALSE, warning = FALSE }
#### MET
plot_aggregated_score(data = results_li, x_var = "preprocessing_mixMET", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)

#### RNA
plot_aggregated_score(data = results_li, x_var = "preprocessing_mixRNA", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```


### FS

```{r combinaisons_aggregated_scores_FS, echo=FALSE,eval=FALSE}
#### MET
plot_aggregated_score(data = results_li, x_var = "feature_selection_mixMET", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)

#### RNA
plot_aggregated_score(data = results_li, x_var = "feature_selection_mixRNA", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```

### DE

```{r combinaisons_aggregated_scores_DE, echo=FALSE,eval=FALSE}
#### MET
plot_aggregated_score(data = results_li, x_var = "deconvolution_met", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)

#### RNA
plot_aggregated_score(data = results_li, x_var = "deconvolution_rna", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```

### LI

```{r combinaisons_aggregated_scores_LI, echo=FALSE,eval=FALSE}
plot_aggregated_score(data = results_li, x_var = "late_integration", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```


## RMSE

```{r common_var_rmse, echo=FALSE,eval=FALSE}
metric = "rmse"
metric_title = "RMSE (-> 0), per dataset"
```


### PP

```{r combinaisons_rmse_PP, echo=FALSE,eval=FALSE, warning = FALSE }
#### MET
plot_aggregated_score(data = results_li, x_var = "preprocessing_mixMET", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)

#### RNA
plot_aggregated_score(data = results_li, x_var = "preprocessing_mixRNA", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```


### FS

```{r combinaisons_rmse_FS, echo=FALSE,eval=FALSE}
#### MET
plot_aggregated_score(data = results_li, x_var = "feature_selection_mixMET", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)

#### RNA
plot_aggregated_score(data = results_li, x_var = "feature_selection_mixRNA", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```

### DE

```{r combinaisons_rmse_DE, echo=FALSE,eval=FALSE}
#### MET
plot_aggregated_score(data = results_li, x_var = "deconvolution_met", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)

#### RNA
plot_aggregated_score(data = results_li, x_var = "deconvolution_rna", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```

### LI

```{r combinaisons_rmse_LI, echo=FALSE,eval=FALSE}
plot_aggregated_score(data = results_li, x_var = "late_integration", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```


## Spearman correlation (row)

```{r common_var_spearman_row, echo=FALSE,eval=FALSE}
metric = "spearman_row"
metric_title = "Spearman correlation (row) (-> 1), per dataset"
```


### PP

```{r combinaisons_spearman_row_PP, echo=FALSE,eval=FALSE, warning = FALSE }
#### MET
plot_aggregated_score(data = results_li, x_var = "preprocessing_mixMET", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)

#### RNA
plot_aggregated_score(data = results_li, x_var = "preprocessing_mixRNA", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```


### FS

```{r combinaisons_spearman_row_FS, echo=FALSE,eval=FALSE}
#### MET
plot_aggregated_score(data = results_li, x_var = "feature_selection_mixMET", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)

#### RNA
plot_aggregated_score(data = results_li, x_var = "feature_selection_mixRNA", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```

### DE

```{r combinaisons_spearman_row_DE, echo=FALSE,eval=FALSE}
#### MET
plot_aggregated_score(data = results_li, x_var = "deconvolution_met", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)

#### RNA
plot_aggregated_score(data = results_li, x_var = "deconvolution_rna", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```

### LI

```{r combinaisons_spearman_row_LI, echo=FALSE,eval=FALSE}
plot_aggregated_score(data = results_li, x_var = "late_integration", y_var = metric, title = metric_title, facet_var = facet_var, add_tooltip_text = add_tooltip_text)
```

